#
# _config.yml for TIL
#

exclude: [ "LICENSE.*", "README.md", "**/*.sh" ]
title: FileFormat.Info Subsite
markdown: kramdown
theme: null
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

google_analytics_id: LATER
ROOT_PREFIX: https://www.fileformat.info/

# used if the ffi location is subdirectory that doesn't exist in the subsection repo
CRUMBTRAIL_PARENTS: []

# used in the crumbtrail link for local directories
LOCAL_INDEX: index.html

# used for nicer text in the crumbtrail
CRUMBTRAIL_TEXT:
  example: Examples
