#
# _config.yml for TIL
#

exclude: [ "**/*.sh" ]
title: FileFormat.Info Subsite
markdown: kramdown
theme: null
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

format_handle: test
format_title: Testing
format_extensions: [ 'test', 'testing']
google_analytics_id: LATER
ROOT_PREFIX: https://www.fileformat.info/
